; Fixes the evaluation of FN to allow for nesting and recursion

_FLAGS:		EQU	01H
ERROR:		EQU	08H
GET_CHAR:	EQU	18H
PARAMETER_ERROR:EQU	19H
NEXT_CHAR:	EQU	20H
CTRL_NUMBER:	EQU	0EH
SCANNING:	EQU	24FBH
S_CONT_2:	EQU	2712H
FN_SKPOVR:	EQU	28ABH
STACK_NUM:	EQU	33B4H
EXCHANGE:	EQU	343CH
STKEND:		EQU	5C65H
DEFADD:		EQU	5C0BH
CH_ADD:		EQU	5C5DH

		ORG	2852H
SF_ARG_VL:	INC	HL
		PUSH	HL
		PUSH	DE
		CALL	SCANNING
		POP	AF
		XOR	(IY+ _FLAGS)
		AND	%01000000
		JR	NZ,REPORT_Q
		POP	HL
		INC	HL
		INC	HL
		INC	HL
		INC	HL
		CALL	FN_SKPOVR
		CP	')'
		JP	Z,SAVARGS
		PUSH	HL
		RST	GET_CHAR
		CP	','
		JR	NZ,REPORT_Q
		RST	NEXT_CHAR
		POP	HL
		CALL	FN_SKPOVR
		JR	SF_ARG_LP
SF_R_BR_2:	PUSH	HL
		RST	GET_CHAR
		CP	')'
		JR	Z,	SF_VALUE
REPORT_Q:	RST	ERROR
		DEFB	PARAMETER_ERROR
SF_VALUE:	POP	DE
		EX	DE,HL
		LD	(CH_ADD),HL
		LD	HL,(DEFADD)
		EX	(SP),HL
		LD	(DEFADD),HL
		PUSH	DE
		RST	NEXT_CHAR
		RST	NEXT_CHAR
		CALL	SCANNING
		LD	DE,(DEFADD)
		CALL	RSTARGS
		POP	HL
		LD	(CH_ADD),HL
		POP	HL
		LD	(DEFADD),HL
		RST	NEXT_CHAR
		JP	S_CONT_2
; 5 spare bytes left


; External routines, need to find extra space for them elsewhere

CNTARTS:	LD	HL,(STKEND)
		LD	BC,5
CNTARG:		LD	A,(DE)
		CP	CTRL_NUMBER
		INC	DE
		JR	NZ,CNOARG
		SBC	HL,BC
		EX	DE,HL
		ADD	HL,BC
		EX	DE,HL
CNOARG:		CP	')'
		JR	NZ,CNTARG
		RET

;--------------------------------

RSTARGS:	PUSH	DE
		CALL	CNTARGS
		SBC	HL,BC
		POP	DE
		PUSH	HL
RESARG:		LD	A,(DE)
		CP	CTRL_NUMBER
		INC	DE
		JR	NZ,RNOARG
		PUSH	BC
		LDIR
		POP	BC
RNOARG:		CP	')'
		JR	NZ,RESARG
		POP	DE
		LD	C,5
		LDIR
		JP	STACK_NUM+7

;--------------------------------

SAVARGS:	POP	DE
		PUSH	DE
		CALL	CNTARGS
		EX	DE,HL
		POP	HL
		PUSH	HL
		LD 	A,(HL)
SAVARG:		INC	HL
		CP	CTRL_NUMBER
		JR	NZ,	SNOARG
		CALL	EXCHANGE
SNOARG:		LD	A,(HL)
		CP	')'
		JR	NZ,SAVARG
		JP	SF_R_BR_2


