COPYRIGHT:
	DEFB	$7F
	DEFM	" 2021 ePoint Systems Ltd"
	DEFB	$8D
; functions, etc.
HEX_T:	EQU	$24	; $
LABEL_T:EQU	$40	; @
TIMES_T:EQU	$5B	; [
OCT_T:	EQU	$5C	; \
MEM_T:	EQU	$5D	; ]
DELETE_T:EQU	$5F	; _
FPOKE_T:EQU	$60	; GBP
ONERR_T:EQU	$7B	; {
STICK_T:EQU	$7C	; |
SOUND_T:EQU	$7D	; }
FREE_T:	EQU	$7E	; ~
RESET_T:EQU	$7F
RND_T:	EQU	$A5
SCREEN_T:EQU	$AA
ATTR_TK:EQU	$AB
AT_T:	EQU	$AC
TAB_T:	EQU	$AD
CODE_T:	EQU	$AF
PEEK_T:	EQU	$BE
USR_T:	EQU	$C0
STR_T:	EQU	$C1
CHR_T:	EQU	$C2
BIN_T:	EQU	$C4
AND_T:	EQU	$C6
LINE_T:	EQU	$CA
THEN_T:	EQU	$CB
TO_T:	EQU	$CC
STEP_T:	EQU	$CD
MERGE_T:EQU	$D5
TIME_T:	EQU	$D5
VERIFY_T:EQU	$D6
REF_T:	EQU	$D6
BEEP_T:	EQU	$D7
CIRCLE_T:EQU	$D8
FPEEK_T:EQU	$D8
INK_T:	EQU	$D9
PAPER_T:EQU	$DA
FLASH_T:EQU	$DB
BRIGHT_T:EQU	$DC
INVERSE_T:EQU	$DD
OVER_T:	EQU	$DE
OUT_T:	EQU	$DF
DPEEK_T:EQU	$DF

TURBO_T:EQU	AT_T
PALETTE_T:EQU	ATTR_TK
DEFPROC_T:EQU	LABEL_T
STOP_T:	EQU	$E2
DATA_T:	EQU	$E4
CONTINUE_T:EQU	$E8
REM_T:	EQU	$EA
FOR_T:	EQU	$EB
GOTO_T:	EQU	$EC
GOSUB_T:EQU	$ED
NEXT_T:	EQU	$F3
POKE_T:	EQU	$F4
IF_T:	EQU	$FA


FN_TABLE:
	DEFB	"["		; TIMES_T
	DEFB	TIMES_M - $
	DEFB	"]"		; MEM_T
	DEFB	MEM_M - $
	DEFB	"|"		; STICK_T
	DEFB	STICK_M - $
	DEFB	"~"		; FREE_T
	DEFB	FREE_M - $
	DEFB	MERGE_T		; TIME_T
	DEFB	TIME_M - $
	DEFB	VERIFY_T	; REF_T
	DEFB	REF_M - $
	DEFB	CIRCLE_T	; FPEEK_T
	DEFB	FPEEK_M - $
	DEFB	OUT_T		; DPEEK_T
	DEFB	DPEEK_M - $
	DEFB	0

TK_TABLE:
	DEFB	"@"		; LABEL_T
	DEFB	LABEL_M - $
	DEFB	"_"		; DELETE_T
	DEFB	DELETE_M - $
	DEFB	FPOKE_T
	DEFB	FPOKE_M - $
	DEFB	"{"		; ONERR_T
	DEFB	ONERR_M - $
	DEFB	"}"		; SOUND_T
	DEFB	SOUND_M - $
	DEFB	RESET_T
	DEFB	RESET_M - $
	DEFB	SCREEN_T
	DEFB	SCREEN_M - $
	DEFB	SPECTRUM_T
	DEFB	SPECTRUM_M - $
	DEFB	PLAY_T
	DEFB	PLAY_M - $
	DEFB	0

; functions
; E s + 'H'
FPEEK_M:DEFM	"FPEEK"
	DEFB	$80+" "

; E s + 'O'
DPEEK_M:DEFM	"DPEEK"
	DEFB	$80+" "

; E s + 'S'
STICK_M:DEFM	"STICK"
	DEFB	$80+" "

; E s + 'Z'
TIMES_M:DEFM	"TIME$"
	DEFB	$80+" "

; E s + 'T'
TIME_M:	DEFM	"TIM"
	DEFB	$80+"E"

; E s + 'R'
REF_M:	DEFM	"REF"
	DEFB	$80+" "

; E s + 'U'
MEM_M:	DEFM	"MEM"
	DEFB	$80+"$"

; E s + 'A'
FREE_M:	DEFM	"FRE"
	DEFB	$80+"E"

; instructions
; s + '2'
LABEL_M:DEFB	$80+"@"

; E s + 'F'
ONERR_M:DEFM	"ON ER"
	DEFB	$80+"R"

; E s + 'P'
RESET_M:DEFM	"RESE"
	DEFB	$80+"T"

; s + '0'
DELETE_M:
	DEFM	"DELET"
	DEFB	$80+"E"

; E s + 'K'
SCREEN_M:DEFM	"DISPLA"
	DEFB	$80+"Y"

; s + 'X'
FPOKE_M:DEFM	"FPOK"
	DEFB	$80+"E"

; E s + 'G'
SOUND_M:DEFM	"SOUN"
	DEFB	$80+"D"

SPECTRUM_T:EQU	$A3
; G 'T'
SPECTRUM_M:DEFM	"SPECTRU"
	DEFB	$80+"M"

PLAY_T:EQU	$A4
; G 'U'
PLAY_M:	DEFM	"PLA"
	DEFB	$80+"Y"
